apiVersion: apps/v1
kind: Deployment
metadata:
  name: deadline
  labels:
    app: deadline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deadline
  template:
    metadata:
      labels:
        app: deadline
    spec:
      containers:
        - name: deadline
          image: "username/deadline:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
